name: ChatCommands
version: 9.2
main: notaro.chatcommands.ChatCommands
author: notaro1997
loadbefore: [Essentials, WorldEdit]
commands:
    leave:
      description: leaves the server.
      -usage: /leave
    join:
      description: joins the server.
      -usage: /join
    afk:
      description: Marks player as AFK.
      -usage: /afk
    fakeop:
      description: fake op a specified player.
      -usage: /fakeop
    hug:
      description: hug a specified player, or don't type a name and hug everyone.
      -usage: /hug
    bitchslap:
      description: Bitchslap a specified player, or don't type a name and bitchslap everyone.
      -usage: /bitchslap
    say:
      description: perform a god msg.
      -usage: /say <MSG>
    clear:
      description: Clear your inv.
      -usage: /clear
    name:
      description: Change your name. (e.g. /name 3 Joe)
      -usage: /name
    position:
      description: get your server position.
      -usage: /position
    inv:
      description: spy on other people inv.
      -usage: /inv
    blind:
      description: Blind a specified player.
      -usage: /blind
    unblind:
      description: Un-Blind a specified player.
      -usage: /unblind
    lll:
      description: makes you high as larry.
      -usage: /lll
    sober:
      description: removes your high.
      -usage: /sober
    superpick:
      description: Presents player with a superpick.
      -usage: /superpick
    boomstick:
      description: Presents player with a boomstick.
      -usage: /boomstick
    heal:
      description: Heal a specified player.
      -usage: /heal
    m:
      description: msg a player.
      -usage: /m <player>
    setspawn:
      description: sets the spawn point.
      -usage: /setspawn
    spawn:
      description: teleports player to spawn.
      -usage: /spawn
    0:
      description: Puts player into gamemode 0.
      -usage: /0
    1:
      description: Puts player into gamemode 1.
      -usage: /1
    2:
      description: Puts player into gamemode 2.
      -usage: /2
    sm:
      description: spawn any mob
      -usage: /sm <mob>
    ban:
      description: Bans a specified player
      -usage: /ban
    kick:
      description: Kick a specified player.
      -usage: /kick
    satan:
      description: perform a satan msg.
      -usage: /satan
    ea:
      description: Toggles exploding arrows.
      -usage: /ea
    killall:
      description: Kill all living entitys.
      -usage: /killall
    invis:
      description: Hides player, and name.
      -usage: /invis
    vis:
      description: Shows player, and name.
      -usage: /vis
    time:
      description: Change time to either day, night, or normal.
      -usage: /time
    tp:
      description: teleport to a specified location.
      -usage: /tp
    summon:
      description: Teleports a player to you.
      -usage: /summon
    hide:
      description: Hides your players tab menu name ect.
      -usage: /hide
    show:
      description: Shows your players name in tab menu ect.
      -usage: /show
    tpblock:
      description: Block teleportation to you.(on, off, status)
      -usage: /tpblock
    weather:
      description: Set the weather.
      -usage: /weather
    enderchest:
      description: View a players enderchest.
      -usage: /enderchest
    lightning:
      description: Strike lightning where your pointing, or a player.
      -usage: /lightning
    info:
      description: Check a player's info.
      -usage: /info
    who:
      description: see who is online.
      -usage: /who
    updatechecker:
      description: Enable or disable UpdateChecker.
      -usage: /updateChecker
    kickall:
      description: Kick all players from the server.
      -usage: /kickall
    kill:
      description: Kill a specified player.
      -usage: /kill
    warp:
      description: Warp to a specified warp.
      -usage: /warp
    setwarp:
      description: Set a specified warp.
      -usage: /setwarp
    delwarp:
      description: Delete a specified warp.
      -usage: /delwarp
    home:
      description: Teleport to your home, or save your home.
      -usage: /home
    sethome:
      description: Set your home where your standing.
      -usage: /sethome